name: Rust

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install nightly
        run: rustup update nightly
      - name: Build
        run: cargo +nightly build --verbose --release